#!/bin/bash
set -euxo pipefail

stack="$1"
bucket="$2"
parameters="$3"

pushd api
  pushd serverless
    for lambda in *; do
      pushd "$lambda"
        npm install
      popd
    done
  popd

  sam package --template-file template.yaml --s3-bucket "$bucket" --output-template-file _out.yaml
  sam deploy --template-file _out.yaml --stack-name "$stack" --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --parameter-overrides "$parameters"
  endpoint=$(aws cloudformation describe-stacks --stack-name "$stack" | jq -r '.Stacks | .[0].Outputs[] | select(.OutputKey == "ApiGatewayEndpoint").OutputValue')
popd

export REACT_APP_ENDPOINT="$endpoint"
npm run build
